//! Materialization for the rules subsystem (REQ-rules-001, REQ-rules-005).
//!
//! - `project init --standard` (no `profile.toml` yet): only the universal
//!   set — `.dec/rules/transversal.yaml` (rules with empty `requires`) plus
//!   a read-only copy of `.dec/rules/profile.schema.yaml`. `profiles/` is
//!   intentionally NOT created.
//! - `spec init` / `profile update` (profile known): mirror norm — group the
//!   **resolved active set** by `primary_flag` and write
//!   `.dec/rules/transversal.yaml` + `.dec/rules/profiles/{flag}.yaml`, each
//!   holding **exactly its active rules** (never inactive candidates), plus
//!   the readable `.dec/rules/active-ruleset.md`.
//!   `realtime` is reference-only (`- ref:` pointers, `rules: []` when none
//!   of its cross-referenced rules is active).
//!
//! Rule bodies are copied verbatim from the embedded catalog (same approach
//! as `rules/partition_rules.py`), so the output stays byte-compatible with
//! the reference in `rules/profiles/`. Writes are write-if-changed, so a
//! second run neither re-asks nor re-materializes. Stale profile files
//! (flag now `false`) are removed; an empty `profiles/` dir is removed.

use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use super::data::{PROFILE_SCHEMA_YAML, RULES_YAML};
use super::model::{load_catalog, ProfileAnswers, Rule, RulesConfig, Severity};
use super::profile::CONDITIONAL_FLAGS;
use super::resolver::{group_by_primary_flag, resolve_active_ruleset, ResolveOptions};

/// Header written above the generated `transversal.yaml`.
const TRANSVERSAL_HEADER: &str = "# .dec/rules/transversal.yaml - schema_version 2\n\
# Generated by: dectl project init --standard from embedded catalog. DO NOT EDIT BY HAND\n\
# (readable cache - the source is embedded RULES_YAML; `dectl rules resync` overwrites).\n";

/// Summary of a [`materialize_all`] run.
#[derive(Debug, Default)]
pub struct MaterializeReport {
    /// Active rules resolved (after `disabled` / `severity_override`).
    pub active_total: usize,
    /// Active rules per severity (MUST, SHOULD, AVOID).
    pub severity_counts: (usize, usize, usize),
    /// Relative paths written (content changed).
    pub written: Vec<String>,
    /// Relative paths left untouched (content identical).
    pub skipped_unchanged: Vec<String>,
    /// Relative paths removed (stale profile for a `false` flag).
    pub removed: Vec<String>,
}

/// Extract verbatim `- id: '...'` blocks whose `primary_flag` is `null`.
fn transversal_blocks() -> Vec<String> {
    let mut out = Vec::new();
    for part in RULES_YAML.split("\n- id: '").skip(1) {
        let block = format!("- id: '{part}").trim_end().to_string();
        // `primary_flag: null` marks a transversal rule (activation lives in
        // `requires`, which is `[]` for these same rules).
        let is_transversal = block.lines().any(|l| l.trim() == "primary_flag: null");
        if is_transversal {
            out.push(block);
        }
    }
    out
}

/// Verbatim catalog block for one rule ID (byte-compatible with
/// `rules/partition_rules.py` output). `None` if the ID is not in the
/// embedded catalog.
fn block_for_id(want: &str) -> Option<String> {
    for part in RULES_YAML.split("\n- id: '").skip(1) {
        let id = part.split('\'').next().unwrap_or("");
        if id == want {
            return Some(format!("- id: '{part}").trim_end().to_string());
        }
    }
    None
}

/// Catalog order index per rule ID (stable, positional — avoids the
/// lexicographic trap, e.g. `13.10` < `13.2`).
fn catalog_order() -> HashMap<String, usize> {
    let mut order = HashMap::new();
    for (i, part) in RULES_YAML.split("\n- id: '").skip(1).enumerate() {
        let id = part.split('\'').next().unwrap_or("");
        order.entry(id.to_string()).or_insert(i);
    }
    order
}

fn sort_catalog_order(rules: &mut [Rule]) {
    let order = catalog_order();
    rules.sort_by_key(|r| order.get(&r.id).copied().unwrap_or(usize::MAX));
}

/// Render the full text of `.dec/rules/transversal.yaml` (schema version 2).
pub fn render_transversal_yaml() -> String {
    let mut text = String::from(TRANSVERSAL_HEADER);
    text.push('\n');
    text.push_str("version: 2\n");
    text.push_str("source: development-rules.md\n");
    text.push_str("generated_by: dectl project init --standard\n");
    text.push_str("rules:\n");
    for block in transversal_blocks() {
        text.push_str(&block);
        text.push('\n');
    }
    text
}

/// Render `transversal.yaml` from an already-resolved active set (mirror:
/// only the active transversal rules — honors `[rules] disabled`).
fn render_transversal_from_rules(active: &[Rule]) -> String {
    let mut rules: Vec<&Rule> = active.iter().filter(|r| r.primary_flag.is_none()).collect();
    let order = catalog_order();
    rules.sort_by_key(|r| order.get(&r.id).copied().unwrap_or(usize::MAX));
    let mut text = String::from(TRANSVERSAL_HEADER);
    text.push('\n');
    text.push_str("version: 2\n");
    text.push_str("source: development-rules.md\n");
    text.push_str("generated_by: dectl project init --standard\n");
    if rules.is_empty() {
        text.push_str("rules: []\n");
        return text;
    }
    text.push_str("rules:\n");
    for rule in rules {
        match block_for_id(&rule.id) {
            Some(block) => {
                text.push_str(&block);
                text.push('\n');
            }
            None => {
                text.push_str(&format!("- id: '{}'\n", rule.id));
            }
        }
    }
    text
}

/// Render a canonical `profiles/{flag}.yaml` from its active rules.
fn render_profile_file(flag: &str, rules: &[Rule]) -> String {
    let mut sorted: Vec<&Rule> = rules.iter().collect();
    let order = catalog_order();
    sorted.sort_by_key(|r| order.get(&r.id).copied().unwrap_or(usize::MAX));
    let mut text = format!("# .dec/rules/profiles/{flag}.yaml - schema_version 2\n");
    text.push_str("# Generated by: dectl spec init from embedded catalog. DO NOT EDIT BY HAND\n");
    text.push_str(
        "# (readable cache - the source is embedded RULES_YAML; `dectl rules resync` overwrites).\n",
    );
    text.push('\n');
    text.push_str("version: 2\n");
    text.push_str(&format!("profile_flag: {flag}\n"));
    if sorted.is_empty() {
        text.push_str("source_rule_ids: []\n");
        text.push_str("rules: []\n");
        return text;
    }
    text.push_str("source_rule_ids:\n");
    for rule in &sorted {
        text.push_str(&format!("- '{}'\n", rule.id));
    }
    text.push_str("rules:\n");
    for rule in &sorted {
        match block_for_id(&rule.id) {
            Some(block) => {
                text.push_str(&block);
                text.push('\n');
            }
            None => {
                text.push_str(&format!("- id: '{}'\n", rule.id));
            }
        }
    }
    text
}

/// Render the reference-only `profiles/realtime.yaml`.
///
/// `refs` holds `(rule_id, canonical_file)` for the **active** rules
/// cross-referenced by `realtime`. Empty refs render `rules: []` (the
/// `realtime`-without-`public_api` case: reachable only by hand-editing
/// `profile.toml`, since the questionnaire skips it via `depends_on`).
fn render_realtime_file(refs: &[(String, String)]) -> String {
    let mut text = String::from("# .dec/rules/profiles/realtime.yaml - schema_version 2\n");
    text.push_str("# Generated by: dectl spec init from embedded catalog. DO NOT EDIT BY HAND\n");
    text.push_str(
        "# Reference-only: canonical content lives in another file (do not duplicate).\n",
    );
    text.push_str("# Activation lives in each rule.requires - this is only physical grouping.\n");
    text.push('\n');
    text.push_str("version: 2\n");
    text.push_str("profile_flag: realtime\n");
    if refs.is_empty() {
        text.push_str("source_rule_ids: []\n");
        text.push_str("rules: []\n");
        return text;
    }
    text.push_str("source_rule_ids:\n");
    for (id, _) in refs {
        text.push_str(&format!("- '{id}'\n"));
    }
    text.push_str("rules:\n");
    for (id, canonical) in refs {
        text.push_str(&format!("- ref: '{id}'\n"));
        text.push_str(&format!("  canonical_file: {canonical}\n"));
    }
    text
}

/// Render the readable `.dec/rules/active-ruleset.md` summary.
pub fn render_active_ruleset_md(active: &[Rule], profile: &ProfileAnswers) -> String {
    let must = active
        .iter()
        .filter(|r| r.severity == Severity::Must)
        .count();
    let should = active
        .iter()
        .filter(|r| r.severity == Severity::Should)
        .count();
    let avoid = active
        .iter()
        .filter(|r| r.severity == Severity::Avoid)
        .count();
    let tier = if profile.handles_pii {
        "CRITICAL"
    } else {
        "STANDARD"
    };
    let mut text = String::from("# Active Ruleset - schema_version 2\n\n");
    text.push_str(
        "<!-- Generated by: dectl spec init from embedded catalog. DO NOT EDIT BY HAND -->\n\n",
    );
    text.push_str("## Profile\n\n");
    text.push_str("| flag | value |\n|------|-------|\n");
    for (flag, value) in [
        ("handles_pii", profile.handles_pii),
        ("has_sql", profile.has_sql),
        ("public_api", profile.public_api),
        ("has_web_ui", profile.has_web_ui),
        ("has_auth", profile.has_auth),
        ("realtime", profile.realtime),
        ("cpu_intensive", profile.cpu_intensive),
        ("long_lived", profile.long_lived),
    ] {
        text.push_str(&format!("| {flag} | {value} |\n"));
    }
    text.push_str(&format!("\ntier_hint = {tier}\n\n"));
    text.push_str("## Counts\n\n");
    text.push_str(&format!("- total: {}\n", active.len()));
    text.push_str(&format!(
        "- MUST: {must}\n- SHOULD: {should}\n- AVOID: {avoid}\n\n"
    ));
    for (title, severity) in [
        ("MUST", Severity::Must),
        ("SHOULD", Severity::Should),
        ("AVOID", Severity::Avoid),
    ] {
        let group: Vec<&Rule> = active.iter().filter(|r| r.severity == severity).collect();
        text.push_str(&format!("## {title} ({})\n\n", group.len()));
        if group.is_empty() {
            text.push_str("_none_\n\n");
            continue;
        }
        for rule in group {
            text.push_str(&format!(
                "- **{}** ({}): {} → {}\n",
                rule.id, rule.section, rule.condition, rule.action
            ));
        }
        text.push('\n');
    }
    text
}

/// Write only when the content differs (idempotent second runs).
/// Returns `true` when the file was written.
fn write_if_changed(
    path: &Path,
    content: &str,
    report_path: &str,
    report: &mut MaterializeReport,
) -> Result<bool> {
    if path.is_file() {
        let current = fs::read_to_string(path)
            .with_context(|| format!("Failed to read {}", path.display()))?;
        if current == content {
            report.skipped_unchanged.push(report_path.to_string());
            return Ok(false);
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory {}", parent.display()))?;
    }
    fs::write(path, content).with_context(|| format!("Failed to write {}", path.display()))?;
    report.written.push(report_path.to_string());
    Ok(true)
}

/// Read per-project `[rules]` customization from `.dec/config/project.toml`
/// (`disabled` + `severity_override`), validated against the catalog.
/// Unknown IDs are an error naming the ID (never silently ignored).
pub fn read_rules_config(project_dir: &Path) -> Result<RulesConfig> {
    let catalog = load_catalog()?;
    let path = project_dir.join(".dec/config/project.toml");
    if !path.is_file() {
        return Ok(RulesConfig::default());
    }
    let content =
        fs::read_to_string(&path).with_context(|| format!("Failed to read {}", path.display()))?;
    let value: toml::Value = toml::from_str(&content)
        .with_context(|| format!("{} is not valid TOML", path.display()))?;
    let config: RulesConfig = match value.get("rules") {
        Some(rules) => rules
            .clone()
            .try_into()
            .with_context(|| format!("[rules] in {} is invalid", path.display()))?,
        None => RulesConfig::default(),
    };
    config.validate(&catalog.rules)?;
    Ok(config)
}

/// Resolve the active ruleset for a project (catalog + profile + `[rules]`).
pub fn resolve_for_project(project_dir: &Path, profile: &ProfileAnswers) -> Result<Vec<Rule>> {
    let catalog = load_catalog()?;
    let config = read_rules_config(project_dir)?;
    let opts = ResolveOptions {
        disabled: &config.disabled,
        severity_override: &config.severity_override,
    };
    Ok(resolve_active_ruleset(&catalog.rules, profile, &opts))
}

/// Mirror the resolved active set to disk (full regeneration):
/// `transversal.yaml` + `profiles/{flag}.yaml` + `active-ruleset.md`.
///
/// - Each profile file holds exactly its active rules (never inactive
///   candidates: `has_auth` without `has_web_ui` omits `13.3`).
/// - Flags in `false` produce no file; stale files are removed. An empty
///   `profiles/` dir is removed (all-false ends with no `profiles/`).
/// - `realtime` is reference-only; with no active cross-referenced rule it
///   renders `rules: []`.
/// - All files carry `version: 2`. Unchanged files are left untouched.
pub fn materialize_all(project_dir: &Path, profile: &ProfileAnswers) -> Result<MaterializeReport> {
    let mut report = MaterializeReport::default();
    let active = resolve_for_project(project_dir, profile)?;
    let must = active
        .iter()
        .filter(|r| r.severity == Severity::Must)
        .count();
    let should = active
        .iter()
        .filter(|r| r.severity == Severity::Should)
        .count();
    let avoid = active
        .iter()
        .filter(|r| r.severity == Severity::Avoid)
        .count();
    report.active_total = active.len();
    report.severity_counts = (must, should, avoid);

    let rules_dir = project_dir.join(".dec/rules");
    fs::create_dir_all(&rules_dir)
        .with_context(|| format!("Failed to create directory {}", rules_dir.display()))?;

    // Transversal mirror (active only — honors `disabled`).
    write_if_changed(
        &rules_dir.join("transversal.yaml"),
        &render_transversal_from_rules(&active),
        ".dec/rules/transversal.yaml",
        &mut report,
    )?;

    // Canonical groups (activation already filtered; grouping is physical).
    let groups = group_by_primary_flag(&active);
    let flags = profile.as_flag_map();
    let mut expected: HashSet<String> = HashSet::new();
    for flag in CONDITIONAL_FLAGS {
        if *flags.get(flag).unwrap_or(&false) && flag != "realtime" {
            expected.insert(flag.to_string());
            let mut rules: Vec<Rule> = groups
                .get(&Some(flag.to_string()))
                .cloned()
                .unwrap_or_default();
            sort_catalog_order(&mut rules);
            write_if_changed(
                &rules_dir.join("profiles").join(format!("{flag}.yaml")),
                &render_profile_file(flag, &rules),
                &format!(".dec/rules/profiles/{flag}.yaml"),
                &mut report,
            )?;
        }
    }

    // Reference-only realtime (refs to active cross-referenced rules).
    if *flags.get("realtime").unwrap_or(&false) {
        expected.insert("realtime".to_string());
        let mut refs: Vec<(String, String)> = active
            .iter()
            .filter(|r| r.cross_referenced_by.contains(&"realtime".to_string()))
            .map(|r| {
                let canonical = match &r.primary_flag {
                    None => "transversal.yaml".to_string(),
                    Some(f) => format!("profiles/{f}.yaml"),
                };
                (r.id.clone(), canonical)
            })
            .collect();
        refs.sort();
        refs.dedup();
        write_if_changed(
            &rules_dir.join("profiles").join("realtime.yaml"),
            &render_realtime_file(&refs),
            ".dec/rules/profiles/realtime.yaml",
            &mut report,
        )?;
    }

    // Stale cleanup: files for flags now `false` (or unknown) are removed.
    let profiles_dir = rules_dir.join("profiles");
    if profiles_dir.is_dir() {
        let mut stale: Vec<PathBuf> = Vec::new();
        for entry in fs::read_dir(&profiles_dir)
            .with_context(|| format!("Failed to list {}", profiles_dir.display()))?
        {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().to_string();
            if !name.ends_with(".yaml") {
                continue;
            }
            let flag = name.trim_end_matches(".yaml");
            if !expected.contains(flag) {
                stale.push(entry.path());
            }
        }
        for path in stale {
            fs::remove_file(&path)
                .with_context(|| format!("Failed to remove stale {}", path.display()))?;
            if let Ok(rel) = path.strip_prefix(project_dir) {
                report.removed.push(rel.display().to_string());
            }
        }
        // All-false ends with no `profiles/` at all.
        let remaining: Vec<_> = fs::read_dir(&profiles_dir)
            .with_context(|| format!("Failed to list {}", profiles_dir.display()))?
            .collect();
        if remaining.is_empty() {
            fs::remove_dir(&profiles_dir)
                .with_context(|| format!("Failed to remove empty {}", profiles_dir.display()))?;
        }
    }

    // Readable summary (always reflects the resolved set).
    write_if_changed(
        &rules_dir.join("active-ruleset.md"),
        &render_active_ruleset_md(&active, profile),
        ".dec/rules/active-ruleset.md",
        &mut report,
    )?;

    Ok(report)
}

/// Write `.dec/rules/transversal.yaml` + `.dec/rules/profile.schema.yaml`.
///
/// Direct-write style (like the SDD bridge in `spec::bridge`): creates
/// `.dec/rules/` on demand, never creates `.dec/rules/profiles/`.
/// Fails only on I/O errors or a drifted embedded catalog (0 transversal
/// rules would mean the catalog lost its schema).
pub fn write_project_init_rules(project_dir: &Path) -> Result<()> {
    let rules_dir = project_dir.join(".dec/rules");
    fs::create_dir_all(&rules_dir)
        .with_context(|| format!("Failed to create directory {}", rules_dir.display()))?;

    let transversal = render_transversal_yaml();
    let count = transversal_blocks().len();
    if count == 0 {
        anyhow::bail!("embedded rules catalog has no transversal rules");
    }
    fs::write(rules_dir.join("transversal.yaml"), &transversal)
        .context("Failed to write .dec/rules/transversal.yaml")?;

    fs::write(rules_dir.join("profile.schema.yaml"), PROFILE_SCHEMA_YAML)
        .context("Failed to write .dec/rules/profile.schema.yaml")?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::super::model::ProfileAnswers;
    use super::*;

    fn profile_with(
        has_sql: bool,
        public_api: bool,
        has_web_ui: bool,
        has_auth: bool,
        realtime: bool,
    ) -> ProfileAnswers {
        ProfileAnswers {
            has_sql,
            public_api,
            has_web_ui,
            has_auth,
            realtime,
            ..Default::default()
        }
    }

    fn write_minimal_project_toml(dir: &Path) {
        fs::create_dir_all(dir.join(".dec/config")).unwrap();
        fs::write(
            dir.join(".dec/config/project.toml"),
            "[project]\nname = \"t\"\n",
        )
        .unwrap();
    }

    #[test]
    fn renders_78_transversal_rules_with_schema_version_2() {
        let blocks = transversal_blocks();
        assert_eq!(
            blocks.len(),
            78,
            "must mirror partition --check (78 transversal)"
        );
        let text = render_transversal_yaml();
        let doc: serde_yaml::Value = serde_yaml::from_str(&text).expect("output must parse");
        assert_eq!(doc.get("version").and_then(|v| v.as_u64()), Some(2));
        assert_eq!(
            doc.get("source").and_then(|v| v.as_str()),
            Some("development-rules.md")
        );
        let rules = doc
            .get("rules")
            .and_then(|v| v.as_sequence())
            .expect("must have a `rules:` sequence");
        assert_eq!(rules.len(), 78);
        assert!(rules.iter().all(|r| r
            .get("requires")
            .and_then(|v| v.as_sequence())
            .map(|s| s.is_empty())
            .unwrap_or(false)));
    }

    #[test]
    fn profile_schema_passthrough_is_verbatim() {
        // Structural keys (stable across the REQ-007 rewording of the
        // questionnaire copy in T036); never assert Spanish strings here.
        assert!(PROFILE_SCHEMA_YAML.contains("questions:"));
        assert!(PROFILE_SCHEMA_YAML.contains("output:"));
    }

    #[test]
    fn generated_headers_carry_no_diacritics() {
        // Anti-regression (REQ-007): code-owned generated strings must stay
        // English/ASCII. Rule bodies (translated in T037) are excluded by
        // rendering with empty rule sets.
        let samples = [
            TRANSVERSAL_HEADER.to_string(),
            render_profile_file("has_sql", &[]),
            render_realtime_file(&[]),
            render_active_ruleset_md(&[], &ProfileAnswers::default()),
        ];
        for s in &samples {
            assert!(
                s.is_ascii(),
                "generated header must be ASCII-only, got:\n{s}"
            );
        }
    }

    #[test]
    fn write_creates_two_files_and_no_profiles_dir() {
        let tmp = tempfile::tempdir().unwrap();
        write_project_init_rules(tmp.path()).unwrap();
        let rules_dir = tmp.path().join(".dec/rules");
        assert!(rules_dir.join("transversal.yaml").is_file());
        assert!(rules_dir.join("profile.schema.yaml").is_file());
        assert!(
            !rules_dir.join("profiles").exists(),
            "profiles/ must NOT be created by project init"
        );
    }

    #[test]
    fn all_false_materializes_no_profiles_dir() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        let report = materialize_all(tmp.path(), &ProfileAnswers::default()).unwrap();
        assert_eq!(report.active_total, 78);
        let rules_dir = tmp.path().join(".dec/rules");
        assert!(rules_dir.join("transversal.yaml").is_file());
        assert!(rules_dir.join("active-ruleset.md").is_file());
        assert!(
            !rules_dir.join("profiles").exists(),
            "all-false must end with no profiles/"
        );
    }

    #[test]
    fn has_auth_without_web_ui_omits_13_3() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        let profile = profile_with(false, false, false, true, false);
        materialize_all(tmp.path(), &profile).unwrap();
        let text =
            fs::read_to_string(tmp.path().join(".dec/rules/profiles/has_auth.yaml")).unwrap();
        let doc: serde_yaml::Value = serde_yaml::from_str(&text).unwrap();
        assert_eq!(doc.get("version").and_then(|v| v.as_u64()), Some(2));
        assert!(
            !text.contains("13.3"),
            "mirror norm: inactive candidate 13.3 must NOT be materialized"
        );
        let rules = doc.get("rules").and_then(|v| v.as_sequence()).unwrap();
        assert_eq!(rules.len(), 6);
    }

    #[test]
    fn enabling_web_ui_adds_13_3_to_existing_has_auth() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        materialize_all(tmp.path(), &profile_with(false, false, false, true, false)).unwrap();
        let before =
            fs::read_to_string(tmp.path().join(".dec/rules/profiles/has_auth.yaml")).unwrap();
        assert!(!before.contains("13.3"));
        // `profile update` regenerates everything from the new set.
        materialize_all(tmp.path(), &profile_with(false, false, true, true, false)).unwrap();
        let after =
            fs::read_to_string(tmp.path().join(".dec/rules/profiles/has_auth.yaml")).unwrap();
        assert!(after.contains("13.3"), "13.3 must join has_auth.yaml");
        assert!(tmp
            .path()
            .join(".dec/rules/profiles/has_web_ui.yaml")
            .is_file());
    }

    #[test]
    fn realtime_without_public_api_renders_empty_rules() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        let profile = profile_with(false, false, false, false, true);
        materialize_all(tmp.path(), &profile).unwrap();
        let text =
            fs::read_to_string(tmp.path().join(".dec/rules/profiles/realtime.yaml")).unwrap();
        let doc: serde_yaml::Value = serde_yaml::from_str(&text).unwrap();
        assert_eq!(doc.get("version").and_then(|v| v.as_u64()), Some(2));
        assert!(
            text.contains("rules: []"),
            "inactive reference must render `rules: []`, got:\n{text}"
        );
        assert!(!text.contains("canonical_file"));
    }

    #[test]
    fn realtime_with_public_api_references_11_4_once() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        let profile = profile_with(false, true, false, false, true);
        materialize_all(tmp.path(), &profile).unwrap();
        let text =
            fs::read_to_string(tmp.path().join(".dec/rules/profiles/realtime.yaml")).unwrap();
        assert!(text.contains("- ref: '11.4'"));
        assert_eq!(text.matches("- ref: '11.4'").count(), 1);
        let public_api =
            fs::read_to_string(tmp.path().join(".dec/rules/profiles/public_api.yaml")).unwrap();
        assert!(
            public_api.contains("11.4"),
            "canonical body lives in public_api.yaml"
        );
    }

    #[test]
    fn materialized_files_carry_version_2_and_active_summary() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        let profile = profile_with(true, false, false, false, false);
        let report = materialize_all(tmp.path(), &profile).unwrap();
        assert_eq!(report.active_total, 81);
        for name in ["transversal.yaml", "profiles/has_sql.yaml"] {
            let text = fs::read_to_string(tmp.path().join(".dec/rules").join(name)).unwrap();
            let doc: serde_yaml::Value = serde_yaml::from_str(&text).unwrap();
            assert_eq!(
                doc.get("version").and_then(|v| v.as_u64()),
                Some(2),
                "{name} must carry version: 2"
            );
        }
        let md = fs::read_to_string(tmp.path().join(".dec/rules/active-ruleset.md")).unwrap();
        assert!(md.contains("schema_version 2"));
        assert!(md.contains("has_sql"));
    }

    #[test]
    fn second_run_skips_unchanged_files() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        let profile = profile_with(true, false, false, false, false);
        let first = materialize_all(tmp.path(), &profile).unwrap();
        assert!(!first.written.is_empty());
        let second = materialize_all(tmp.path(), &profile).unwrap();
        assert!(
            second.written.is_empty(),
            "double run must not re-materialize: {:?}",
            second.written
        );
        assert!(!second.skipped_unchanged.is_empty());
    }

    #[test]
    fn disabling_flag_removes_its_stale_file() {
        let tmp = tempfile::tempdir().unwrap();
        write_minimal_project_toml(tmp.path());
        materialize_all(tmp.path(), &profile_with(true, false, false, false, false)).unwrap();
        assert!(tmp
            .path()
            .join(".dec/rules/profiles/has_sql.yaml")
            .is_file());
        let report = materialize_all(tmp.path(), &ProfileAnswers::default()).unwrap();
        assert!(!tmp.path().join(".dec/rules/profiles/has_sql.yaml").exists());
        assert!(report.removed.iter().any(|p| p.contains("has_sql.yaml")));
    }

    #[test]
    fn unknown_rule_id_in_project_toml_errors_with_id() {
        let tmp = tempfile::tempdir().unwrap();
        fs::create_dir_all(tmp.path().join(".dec/config")).unwrap();
        fs::write(
            tmp.path().join(".dec/config/project.toml"),
            "[project]\nname = \"t\"\n[rules]\ndisabled = [\"99.9\"]\n",
        )
        .unwrap();
        let err = read_rules_config(tmp.path()).unwrap_err().to_string();
        assert!(err.contains("99.9"), "error must name the ID: {err}");
    }
}
