use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::bail_app_err;
use crate::spec::add::ExtractedReqs;

static REQ_TEMPLATE: &str = r#"
### REQ-{NUMBER}: {TITLE}
**User Story**:
> {USER_STORY}

**Acceptance Criteria**:
{CRITERIA}

**Implementation Notes**: This requirement SHALL be implemented as 2–3 atomic, individually verifiable tasks. Each task must compile and verify before the next begins.

---
"#;

static TASK_TEMPLATE: &str = r#"- [ ] [T{NUMBER}] [Feature] {TITLE} — M (REQ-{REQ_NUM})
  **Build**: `cargo build` passes without errors
  **Verify**: `cargo test` passes for the module
  **Gate**: must pass before T{NEXT}
"#;

pub fn run(name: &str, reqs: &ExtractedReqs) -> Result<()> {
    let specs_dir = Path::new("specs");
    if !specs_dir.exists() {
        bail_app_err!(
            "specs/ directory not found",
            "Run `dectl spec init` first to create the SDD structure"
        );
    }

    let spec_path = specs_dir.join("spec.md");
    let tasks_path = specs_dir.join("tasks.md");

    append_to_spec(&spec_path, reqs)?;
    append_to_tasks(&tasks_path, reqs)?;

    println!(
        "✅ Added feature '{}' to specs/ ({} REQ(s))",
        name,
        reqs.requirements.len()
    );
    Ok(())
}

fn append_to_spec(path: &Path, reqs: &ExtractedReqs) -> Result<()> {
    let mut content = if path.exists() {
        fs::read_to_string(path).context("Failed to read spec.md")?
    } else {
        let header = format!(
            "# Spec: {}\n> *Auto-generated by `dectl spec add`.*\n\n## Functional Requirements\n",
            reqs.name
        );
        header
    };

    let next_req_num = find_last_req_number(&content) + 1;

    for (i, req) in reqs.requirements.iter().enumerate() {
        let number = next_req_num + i;
        let criteria_lines = if req.acceptance_criteria.is_empty() {
            "  - WHEN (condition) THEN the system SHALL (behavior)".to_string()
        } else {
            req.acceptance_criteria
                .iter()
                .map(|c| format!("  {}", c))
                .collect::<Vec<_>>()
                .join("\n")
        };
        let user_story = if req.user_story.is_empty() {
            format!(
                "As a developer, I want {} so that it works correctly.",
                req.title.to_lowercase()
            )
        } else {
            req.user_story.clone()
        };
        let block = REQ_TEMPLATE
            .replace("{NUMBER}", &format!("{:03}", number))
            .replace("{TITLE}", &req.title)
            .replace("{USER_STORY}", &user_story)
            .replace("{CRITERIA}", &criteria_lines);
        content.push_str(&block);
    }

    fs::write(path, content.as_bytes()).context("Failed to write spec.md")?;
    Ok(())
}

fn append_to_tasks(path: &Path, reqs: &ExtractedReqs) -> Result<()> {
    let mut content = if path.exists() {
        fs::read_to_string(path).context("Failed to read tasks.md")?
    } else {
        let header = format!(
            "# Tasks: {}\n> *Auto-generated by `dectl spec add`.*\n\n## Phase 1: Implementation\n\n",
            reqs.name
        );
        header
    };

    let next_task_num = find_last_task_number(&content) + 1;

    for (i, req) in reqs.requirements.iter().enumerate() {
        let task_num = next_task_num + i;
        let req_num = find_last_req_number_for_tasks(&content, req);
        let task = TASK_TEMPLATE
            .replace("{NUMBER}", &format!("{:03}", task_num))
            .replace("{TITLE}", &format!("Implement {}", req.title))
            .replace("{REQ_NUM}", &format!("{:03}", req_num))
            .replace("{NEXT}", &format!("{:03}", task_num + 1));
        content.push_str(&task);
    }

    fs::write(path, content.as_bytes()).context("Failed to write tasks.md")?;
    Ok(())
}

fn find_last_req_number(content: &str) -> usize {
    let re = regex::Regex::new(r"REQ-(?:\w+-)?(\d+)").unwrap();
    re.captures_iter(content)
        .filter_map(|c| c.get(1)?.as_str().parse::<usize>().ok())
        .max()
        .unwrap_or(0)
}

fn find_last_task_number(content: &str) -> usize {
    let re = regex::Regex::new(r"\[T(\d+)\]").unwrap();
    re.captures_iter(content)
        .filter_map(|c| c.get(1)?.as_str().parse::<usize>().ok())
        .max()
        .unwrap_or(0)
}

fn find_last_req_number_for_tasks(content: &str, req: &crate::spec::add::Requirement) -> usize {
    if let Some(num_str) = req.id.split('-').next_back() {
        if let Ok(num) = num_str.parse::<usize>() {
            return num;
        }
    }
    find_last_req_number(content)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_find_last_req_number_empty() {
        assert_eq!(find_last_req_number(""), 0);
    }

    #[test]
    fn test_find_last_req_number_simple() {
        let content = "### REQ-001: Login\n### REQ-005: Logout\n";
        assert_eq!(find_last_req_number(content), 5);
    }

    #[test]
    fn test_find_last_req_number_with_prefix() {
        let content = "### REQ-C-010: CLI\n### REQ-C-023: Memory\n";
        assert_eq!(find_last_req_number(content), 23);
    }

    #[test]
    fn test_find_last_task_number_empty() {
        assert_eq!(find_last_task_number(""), 0);
    }

    #[test]
    fn test_find_last_task_number() {
        let content = "- [ ] [T001] Setup\n- [x] [T042] Core\n";
        assert_eq!(find_last_task_number(content), 42);
    }

    #[test]
    fn test_find_last_task_number_with_prefix() {
        let content = "- [ ] [C001] CLI\n- [ ] [C015] Memory\n";
        assert_eq!(find_last_task_number(content), 0);
    }

    #[test]
    fn test_append_to_spec_creates_new_file() {
        let dir = std::env::temp_dir().join("dectl_test_feature_spec");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let spec_path = dir.join("spec.md");
        let reqs = ExtractedReqs {
            name: "test".into(),
            description: String::new(),
            requirements: vec![crate::spec::add::Requirement {
                id: "REQ-001".into(),
                title: "Login".into(),
                user_story: "As a user, I want to log in.".into(),
                acceptance_criteria: vec![],
            }],
        };

        append_to_spec(&spec_path, &reqs).unwrap();
        assert!(spec_path.exists());
        let content = fs::read_to_string(&spec_path).unwrap();
        assert!(content.contains("REQ-001"));
        assert!(content.contains("Login"));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_append_to_spec_appends_existing() {
        let dir = std::env::temp_dir().join("dectl_test_feature_append");
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let spec_path = dir.join("spec.md");
        fs::write(&spec_path, "### REQ-005: Existing\n\n---\n").unwrap();

        let reqs = ExtractedReqs {
            name: "test".into(),
            description: String::new(),
            requirements: vec![crate::spec::add::Requirement {
                id: "REQ-006".into(),
                title: "New Feature".into(),
                user_story: "As a user, I want new.".into(),
                acceptance_criteria: vec![],
            }],
        };

        append_to_spec(&spec_path, &reqs).unwrap();
        let content = fs::read_to_string(&spec_path).unwrap();
        assert!(content.contains("REQ-005"));
        assert!(content.contains("REQ-006"));

        let _ = fs::remove_dir_all(&dir);
    }
}
