name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-musl

      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Rename
        run: |
          cp target/x86_64-unknown-linux-musl/release/dectl dectl-linux-x86_64
          chmod +x dectl-linux-x86_64

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dectl-linux-x86_64
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Rename
        run: |
          cp target/release/dectl dectl-macos-x86_64
          chmod +x dectl-macos-x86_64

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: dectl-macos-x86_64
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}